# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 256652c9fa24d26e3bdf9348dd18643ff54b55f6c28c5ee6d0d1ce31324989593e5d4643bde42c78ffdfbc870f32d0e1b52a3ab3f8f34fb1252d2715379cabe9

test:
  secret_key_base: c29216a7f9af850c26a3af6abba803303d5a4df66d0a070254f8b0a61a810573ed39d15025056522722b957732f928ac1bd5640d30ff6a1fd857b2fd60e420b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
